/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mincut_MincutJNI */

#ifndef _Included_mincut_MincutJNI
#define _Included_mincut_MincutJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mincut_MincutJNI
 * Method:    minCut
 * Signature: ([[D[[DI)[I
 */
JNIEXPORT jintArray JNICALL Java_mincut_MincutJNI_minCut
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
